env: flex
runtime: gs://elixir-runtime/elixir.yaml
runtime_config:
    release_app: app
beta_settings:
    cloud_sql_instances: [harvest:us-central1:main]
env_variables:
    DATABASE_USER: postgres
    DATABASE_NAME: harvest-prod
    DATABASE_SOCKET_DIR: /cloudsql/harvest:us-central1:main
skip_files:
    - ^node_modules/.*$
