steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/app:$SHORT_SHA", "--build-arg", "project_id=$PROJECT_ID", "."]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
images: ["gcr.io/$PROJECT_ID/app:$SHORT_SHA"]
