version: '2.1'
services:
  app:
    links:
      - redis
      - postgres
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    ports:
      - 4000:4000
    build:
      context: .
      dockerfile: Dockerfile.test
    restart: on-failure
    environment:
      DATABASE_USER=postgres
      DATABASE_PASS=postgres
      DATABASE_NAME=harvest_test
      DATABASE_HOST=postgres
  redis:
    image: bitnami/redis:5.0
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  postgres:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=harvest_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "exit 0"
