# The version of Alpine to use for the final image
# This should match the version of Alpine that the `elixir:1.7.2-alpine` image uses
ARG ALPINE_VERSION=3.8

FROM elixir:1.7.2-alpine AS builder

RUN MIX_ENV=prod mix do deps.get, deps.compile, compile
RUN MIX_ENV=prod mix release --env lambda --name harvest

ENTRYPOINT ["mix"]
CMD ["release", "--env=prod"]
