FROM bitwalker/alpine-elixir-phoenix

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV MIX_ENV=test

# By convention, /opt is typically used for applications
WORKDIR /opt/app

# This step installs all the build tools we'll need
RUN apk update && \
    apk upgrade --no-cache && \
    apk add --no-cache \
    git \
    build-base && \
    mix local.rebar --force && \
    mix local.hex --force

# This copies our app source code into the build container
COPY . .

RUN mix do deps.get, deps.compile

ENTRYPOINT ["mix"]
CMD ["test"]
